GET http://localhost:3001/todos

###
POST http://localhost:3001/todos/new
Content-Type: application/json

{
  "text": "Get the Bread"
}

###
DELETE http://localhost:3001/todo/delete/65b5c8e4816f8641a611e242

###
PUT http://localhost:3001/todo/complete/65b6f630cdce9e369a54bc76