GET http://localhost:3001/todos

###
POST http://localhost:3001/todos/new
Content-Type: application/json

{
  "text": "Get the Milk"
}

###
DELETE http://localhost:3001/todo/delete/65b5c8e4816f8641a611e242