GET http://localhost:3001/todos

###
POST http://localhost:3001/todos/new
Content-Type: application/json

{
  "text": "clean up charlie shit"
}

###
DELETE http://localhost:3001/todo/delete/65b6f623cdce9e369a54bc73

###
# set to complete
PUT http://localhost:3001/todo/complete/65b6f630cdce9e369a54bc76
